### ISSUE TITLE
Treemap : Show child element data at parent level

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#405] opened 2016-01-06 14:40 UTC
Hi,

Is there a way to show the child element data at parent level using d3Plus ?

Reference: https://finviz.com/map.ashx?t=sec 
In the above example, GOOGL is the child data of Technology. 

Thanks

**Comment by heenamahour** [comment] 2016-01-06 15:51
I think it could be achieved by depth() . Please correct me if I am wrong. 
Also, is there a way to display the parent name at deeper nesting, similar to the way Technology is displayed over GOOGL and other deeper nesting data.

**Comment by davelandry** [comment] 2016-01-22 20:55
The [.depth( )](https://github.com/alexandersimoes/d3plus/wiki/Visualizations#depth) method will show children data grouped by parents.

Displaying the parent name is a duplicate of #363.

**Closed by davelandry** 2016-01-22 20:55 UTC
