### ISSUE TITLE
legend range does not update when clicking the additional values rectangle

### ISSUE THREAD

**Issue by m-ibm** [alexandersimoes/d3plus#509] opened 2016-07-06 14:45 UTC
I title pretty much says it all; the legend range might be incorrect when min/max is under the additional values rectangle.

I have a case where the size of the rectangles is based on field X and the legend on field Y.
It also happens that the objects with (both) min/max values of Y are small enough to be bundled under the 'Values < zzz' rectangle.

The legend displays the min/max as those of the shown values, which _could_ be fine **if** the legend would update when drilling in, and that does not happen.
Since it makes sense that the legend boundaries are static, it should generate the ticks taking into account **all** objects, not only the displayed ones.

**Comment by davelandry** [comment] 2016-07-06 16:31
I'm not following some of this, can you post a code snippit showing the problem?

**Comment by m-ibm** [comment] 2016-07-18 10:38
The below treemap definition is only part of what we use, but should be enough to explain this issue.

			treeMap = d3plus.viz()
			.container("#viz")
			.data(data)
			.size( {
				"value":"Y",
				"threshold":true
			})
			.type("tree_map")
			.aggs( { "X" : "mean" } )
			.legend( { "value" : true } )

When we have a few hundred data points, the tree-map will have the 'others' rectangle.
Assume that the values of X are between 1 and 10. The legend should be between these values.
However, if for example. all values of 0 (or 10) are on data points hidden in the 'others' rectangle the legend will display 1-10 (or 0-9) instead of 0-10.

This appears to happen because the calculation of the legend occurs only after filtering the data to be displayed. This calculation is only performed once, so drilling in will not change the boundaries.

The fix should be simple - consider **all** the data when deciding on the min/max values for the legend.

**Comment by davelandry** [comment] 2016-07-22 20:03
If I'm understanding you correctly, this is expected behavior.

Set aside the "threshold" option for a second, and consider simple nesting. Given this configuration:

```html
<div id="viz"></div>
```

```js
var data = [
  {value: 10, parent: 1, id: "a"},
  {value: 30, parent: 1, id: "b"},
  {value: 20, parent: 2, id: "c"}
];

d3plus.viz()
  .container("#viz")
  .color("value")
  .data(data)
  .id("parent")
  .size("value")
  .type("tree_map")
  .draw();
```

The visible color scale here goes from 20 to 40, which is correct given the groupings that are occurring. Even though there is a data point with a value of 10, it is being visually represented as it's parent group, which has a summed value of 40.

**Comment by m-ibm** [comment] 2016-07-24 08:36
My point is that the _legend_ is incorrect, not the aggregation.
In your example there will be no color for value 10 even when expanding parent 1. This is not what the user expects.
The legend should **always** represent all the values in the data, regardless of the aggregation.
If (and this isn't happening as far as I can tell) the legend would be updated when expanding parent 1, then it is arguably correct though, as a user, I would find it somewhat confusing to see the legend change (note that I mentioned color and size as different data fields).

**Comment by davelandry** [comment] 2016-08-12 14:29
I'm sorry, that snippet of code I posted is missing a crucial line:

```js
var data = [
  {value: 10, parent: 1, id: "a"},
  {value: 30, parent: 1, id: "b"},
  {value: 20, parent: 2, id: "c"}
];

d3plus.viz()
  .container("#viz")
  .color("value")
  .data(data)
  .id(["parent", "id"])
  .size("value")
  .type("tree_map")
  .draw();
```

When you give the .id( ) method an array of IDs, it properly nests the data and updates the scale when zooming. Here is what it looks like at the parent level, with color scale from 20 to 40:

<img width="787" alt="screen shot 2016-08-12 at 10 25 05 am" src="https://cloud.githubusercontent.com/assets/1847581/17625551/61f74ee8-6077-11e6-9d1f-7c13ab829173.png">

And then once clicking on parent 1, the scale updates to 10 to 30:
<img width="784" alt="screen shot 2016-08-12 at 10 25 30 am" src="https://cloud.githubusercontent.com/assets/1847581/17625558/69156ec6-6077-11e6-8440-3a96d9700692.png">

Let me know if that's not what you are seeing, or what you'd expect the scale ranges to be for each level.

**Comment by m-ibm** [comment] 2016-08-15 11:55
Your example works as expected.
However, my (specific) data does not have nesting levels. The nesting is implicit by having too many rectangles to display, thus the `other` rectangle appears.

What I see is the legend being drawn with values that **don't** include the actual data *min* and *max*. This could be fine as **in my example** min and max happen to be inside the `other` rectangle whose legend value is defined by the mean of its contents.
However, the redraw when drilling into the `other` rectangle has he **same** values; I would expect a different range, especially since now *min* and *max* are not aggregated with anything.

In the general case, whether or not the `other` rectangle is displayed, I would expect to see a legend with the min/max range of the original data.
I think this is orthogonal to whether the data has nesting levels or not.

**Comment by davelandry** [comment] 2016-08-16 15:14
Ahh I see, thanks for clarifying. I was able to fix it so that the legend scale updates when clicking on the `other` rectangle. Will be part of next release.

**Closed** 2016-08-16 15:14 UTC
