### ISSUE TITLE
Markers in geomap

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#393] opened 2015-12-05 20:42 UTC
It will be great to implement marker in geomap, it will help to depict unions.
Please let me know if unions such as "European union" could be represented in the latest version of geomap 

Thanks :)

**Comment by davelandry** [comment] 2015-12-07 16:16
What do mean by markers? Can you post an example map?

**Comment by heenamahour** [comment] 2015-12-07 16:31
Hi @davelandry , 

Please refer https://developers.google.com/chart/interactive/docs/gallery/geomap?hl=en for markers

Thanks

**Comment by lokidg** [comment] 2015-12-07 16:34
Heena and Dave, you know gogeo.io it's a cloud geo bigdata platform, they
already have some interesting features for maps, maybe Heena could take a
look at?

Tiago
ᐧ

**Comment by davelandry** [comment] 2015-12-07 18:35
Ahh yes, points drawn given lat/long coordinates. This is a duplicate of issue #86.

**Closed by davelandry** 2015-12-07 18:35 UTC
