### ISSUE TITLE
show logo instead of text inside map nations

### ISSUE THREAD

**Issue by francescoagati** [alexandersimoes/d3plus#346] opened 2015-06-26 15:01 UTC
Hi,
is possible show images inside maps instead of text name nations?

**Comment by davelandry** [comment] 2015-06-26 17:07
Unfortunately, no not currently.

Closing as a duplicate of this issue: https://github.com/alexandersimoes/d3plus/issues/317

**Closed by davelandry** 2015-06-26 17:07 UTC
