### ISSUE TITLE
branch header in treemap 

### ISSUE THREAD

**Issue by heenamahour** [alexandersimoes/d3plus#406] opened 2016-01-07 14:00 UTC
Is there a way to display branch header in treemap using d3plus ? 

For eg : 
![image](https://cloud.githubusercontent.com/assets/16151074/12172143/13c500b0-b575-11e5-86bd-ac1c3e3433bd.png)

**Comment by davelandry** [comment] 2016-01-22 20:58
duplicate of #363

**Closed by davelandry** 2016-01-22 20:58 UTC
