### ISSUE TITLE
infinite draw loop when trying to change multiple ui variables

### ISSUE THREAD

**Issue by artenator** [alexandersimoes/d3plus#484] opened 2016-05-27 02:08 UTC
var visualization = d3plus.viz()
    .container("#viz")
    .data(data)
    .type("scatter")
    .id(["alcohol","name"])
    .aggs({"quality": "mean"})
    .x("alcohol")
    .tooltip(true)
    .y("quality")
    .tooltip({"name" : "name"})
    .tooltip({"children" : false})
    //.size("count")
    .size(20)
    //.nodes({"overlap" : 0.5})
    .ui([
        {
            "method" : function(value, viz){
              viz.x(value).id(value).draw();
        },
            "label": "test",
            "type": "drop",
            "value"  : [{"alcohol": "alcohol"}, {"sulphates": "sulphates"}]
        }
    ])
    .draw()

When I click sulphates or alcohol on the dropdown menu, my visualization gets into an infinite loop of reinitializing/redrawing. I am not sure if this is a bug or if I am doing it incorrectly.

Works fine when I do something like "method" : "id", but i need to change both id and x at once.

Thanks!

**Comment by davelandry** [comment] 2016-05-31 01:42
Can you post your full code, with the dataset used? I see that you're initially setting ID to `["alcohol","name"]`, but then in the UI you're setting it to a single value, maybe that's the culprit?

**Comment by davelandry** [comment] 2016-05-31 21:03
duplicate of #452

**Closed by davelandry** 2016-05-31 21:03 UTC
