### ISSUE TITLE
Changing prefixed labels and text

### ISSUE THREAD

**Issue by dannice** [alexandersimoes/d3plus#655] opened 2018-08-30 10:10 UTC
I need to translate a few labels and text that is prefixed.

See image:
![issue1](https://user-images.githubusercontent.com/2592743/44845348-d2d52780-ac3c-11e8-893b-c0dbc25f5e39.PNG)

Is it possible? Did not get this function to work:
```
d3plus.viz()
.format({
"text": function(text, params) {
if (text === "Share") { return "StringOfYourLanguage"; } }})
```

**Comment by davelandry** [comment] 2018-08-30 18:36
duplicate of #653

**Closed by davelandry** 2018-08-30 18:36 UTC
