### ISSUE TITLE
Using svg textwrap with polygons

### ISSUE THREAD

**Issue by ebwalker** [alexandersimoes/d3plus#478] opened 2016-05-11 16:49 UTC
Is it possible to use the textwrap feature with an svg <polygon>? The <rect> and <circle> work very well, but wanted to do this with a svg polygon shape that looks like a text-bubble. Thank you!

**Comment by curran** [comment] 2016-05-12 07:25
I've often wondered about this too - particularly if the textwrap feature could possibly be used to label streamgraphs.

Possibly a duplicate of https://github.com/d3plus/d3plus-text/issues/6

**Comment by ebwalker** [comment] 2016-05-12 18:57
Thanks @curran! I will dig through this thread and see if I can make it work. I really appreciate the quick response.

**Comment by davelandry** [comment] 2016-05-23 21:07
Have you guys seen the largestRect function? It's available with `d3plus.geom.largestRect`:
* [Blog Post and Examples](http://d3plus.org/blog/behind-the-scenes/2014/07/08/largest-rect/)
* [Documentation](https://github.com/alexandersimoes/d3plus/wiki/Geometry%20Utilities#largestRect)

Internally, D3plus uses it for stacked area charts. Here's the code: https://github.com/alexandersimoes/d3plus/blob/master/src/viz/helpers/shapes/area.js#L50-L72

I'm going to close this issue in favor of [this new issue](https://github.com/d3plus/d3plus-text/issues/16) in the 2.0 d3plus-text module.

**Closed by davelandry** 2016-05-23 21:07 UTC
