### ISSUE TITLE
Zoom Controls

### ISSUE THREAD

**Issue by ltoole** [alexandersimoes/d3plus#314] opened 2015-04-23 19:26 UTC
For users that are less mouse centric, are there map zoom controls (+/-) that can be included in geomap visualizations?

**Comment by davelandry** [comment] 2015-04-23 21:31
Duplicate of #76

**Closed by davelandry** 2015-04-23 21:31 UTC

**Comment by ltoole** [comment] 2015-04-23 21:41
Thanks for getting back to me, but I don't understand the resolution of #76? Are there zoom controls available or are they coming? I don't think they are needed, but I've had two people use the geomap visualization not knowing how to zoom in and out with current mouse implementation.

**Comment by davelandry** [comment] 2015-04-23 22:29
They are not available, but are coming. Issue #76 is still open, and I'll update it with more specifics.
