### ISSUE TITLE
D3Plus Network does not show self loop

### ISSUE THREAD

**Issue by vishrantgupta** [alexandersimoes/d3plus#636] opened 2018-03-21 21:52 UTC
Below is a sample code:

If you observe there is self-loop from eta to eta, but in visualization, it is not shown.

```
<!doctype html>
<meta charset="utf-8">

<script src="http://d3plus.org/js/d3.js"></script>
<script src="http://d3plus.org/js/d3plus.js"></script>

<div id="viz"></div>

<script>

  var sample_data = [
    {"name": "alpha", "size": 10},
    {"name": "beta", "size": 12},
    {"name": "gamma", "size": 30},
    {"name": "delta", "size": 26},
    {"name": "epsilon", "size": 12},
    {"name": "zeta", "size": 26},
    {"name": "theta", "size": 11},
    {"name": "eta", "size": 24}
  ]

  var connections = [
    {"source": "alpha", "target": "beta"},
    {"source": "alpha", "target": "gamma"},
    {"source": "beta", "target": "delta"},
    {"source": "beta", "target": "epsilon"},
    {"source": "zeta", "target": "gamma"},
    {"source": "theta", "target": "gamma"},
    {"source": "eta", "target": "gamma"},
	{"source": "eta", "target": "eta"}
  ]

  var visualization = d3plus.viz()
    .container("#viz")
    .type("network")
    .data(sample_data)
    .edges(connections)
    .size("size")
    .id("name")
	.edges({"arrows": true})
    .draw()

</script>
```

![image](https://user-images.githubusercontent.com/1741243/37739499-4416648e-2d28-11e8-9b25-f70bfb055f14.png)

I was expecting something like as follows for eta node:

![image](https://user-images.githubusercontent.com/1741243/37739614-b0ddffb4-2d28-11e8-92e4-f18ecba3a6f5.png)

**Comment by davelandry** [comment] 2018-04-02 14:49
duplicate of #566

**Closed by davelandry** 2018-04-02 14:49 UTC
